---
  - name: Sets timezone to Denver.
    command: timedatectl set-timezone America/Denver
    become: true

  - name: Update APT package manager repositories cache.
    apt:
      update_cache: yes
    become: true

  - name: Installing common tools.
    apt:
      name: ['htop', 'unzip', 'ntp', 'vim']
      state: present
    become: true
